---
title: "midterm"
author: "Daoyang E"
date: "2020/3/30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(forcats)
```

### Question 1
```{r}
poll16 <- read.csv("C:/Users/China/Desktop/QTM 151/midterm/poll16.csv")
View(poll16)
```

```{r}
newpoll <- poll16[-c(1,2),]
poll <- newpoll %>% separate(Sample, into = c("number", "LR"), sep=-2) 
poll$number <-  as.numeric(poll$number)
```

```{r}
poll1 <- poll %>% group_by(Poll)%>%summarise(total = sum(number,na.rm = T))
```

```{r}
ggplot(poll1, aes(x=total, y=fct_reorder(Poll, total))) +
  geom_point()+
  labs(title = "Distribution of numbers with polls",
       x = "total number",
       y = "poll firms")
```

```{r}
poll1%>%arrange(desc(total)) %>% top_n(3)
```


### Question 2
```{r}
poll2<- poll %>% filter(Poll %in% c("NBC News/SMNBC News","LA Times/USC TrackingLA Times","Reuters/IpsosReuters"))%>%separate(Date, into = c("startdate", "enddate"), sep="/") %>% mutate(diff = Clinton - Trump)
```

```{r}
ggplot(poll2,aes(x = enddate, y = diff))+
  geom_point(aes(color = Poll, shape = Poll))+
  theme(legend.position = "bottom",axis.text.x = element_text(size=10, angle=45))+
  labs(title = "difference between the three polls on Clinton Trump support rate", x = "Enddate", y = "Difference between Clinton and Trump rate")
```


### Question 3
```{r}
poll3 <- poll %>% filter(Poll %in% c("NBC News/SMNBC News"))%>%separate(Date, into = c("startdate", "enddate"), sep="/")%>%gather('Clinton','Trump',key = Candidates, value = rates)
```

```{r}
ggplot(poll3,aes(x = enddate, y = rates))+
  geom_point(aes(color = Candidates))+
  theme(legend.position = "bottom",axis.text.x = element_text(size=10, angle=45))+
  labs(title = "Cliton and Trump rates from NBC news", x = "Enddate", y = "Clinton and Trump rate")
```

